allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: true
  sharp: true

ignoredBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - protobufjs
  - sharp
